littlelemon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('api/', include('littlelemonAPI.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/registration/', include('djoser.urls.authtoken'))
]

littlelemonAPI/urls.py
from django.urls import path, include
from . import views

app_name = 'littlelemonAPI'

urlpatterns = [
    path('menu/', views.MenuItemAPIView.as_view(), name='menu-api'),
    path('menu-items/<int:pk>/', views.SingleMenuItemAPIView.as_view(), name='menu-items-api'),
    path('bookings/', views.BookingAPIView.as_view(), name="bookings-api")
]

restaurant/urls.py
from django.urls import path, include
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('book/', views.book, name="book"),
    path('reservations/', views.Reservation.as_view(), name="reservations"),
    path('menu/', views.Menu.as_view(), name='menu'),
    path('menu-items/<int:id>', views.SingleMenuItem.as_view(), name='menu-item'),
]

littlelemonAPI/models.py
from django.db import models

# Create your models here.
class Booking(models.Model):
    name = models.CharField(max_length=255)
    reservation_date = models.DateTimeField()
    reservation_slot = models.SmallIntegerField(default=10)
    no_of_guests = models.IntegerField(default=1)
    
    def __str__(self): 
        return self.name

    class Meta:
        unique_together = ('reservation_date', 'reservation_slot')
        
class Menu(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    menu_item_description = models.TextField(max_length=1000, default='')
    inventory = models.IntegerField()
    
    def __str__(self): 
        return f'{self.title} : {str(self.inventory)}'
    

littlelemonAPI/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, AllowAny

from datetime import datetime

from .models import Menu, Booking
from .serializers import MenuItemSerializer, BookingSerializer

# Create your views here.

class MenuItemAPIView(ListCreateAPIView):
    queryset = Menu.objects.all()
    serializer_class = MenuItemSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

class BookingAPIView(ListCreateAPIView):
    queryset = Booking.objects.all()
    serializer_class = BookingSerializer
    permission_classes = [AllowAny]
    
    def get(self, request, *args, **kwargs):
        reservation_date = self.request.query_params.get('date', datetime.today().date())    
        self.queryset = self.queryset.filter(reservation_date=reservation_date)

        return super().get(request, *args, **kwargs)
    
class SingleMenuItemAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Menu.objects.all()
    serializer_class = MenuItemSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

restaurant/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views import View
from django.http import Http404

import json

from littlelemonAPI.serializers  import BookingSerializer, MenuItemSerializer
from littlelemonAPI.models import Booking, Menu as MenuModel

# Create your views here.
def home(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def book(request):
    return render(request, 'book.html')

class Reservation(View):
    template_name = 'reservations.html'

    def get(self, request):
        bookings = Booking.objects.all()
        booking_json = BookingSerializer(data=bookings, many=True)
        booking_json.is_valid()

        return render(request, self.template_name, {"bookings": json.dumps(booking_json.data)})

class Menu(View):
    template_name = 'menu.html'

    def get(self, request):
        menu = MenuModel.objects.all()
        menu_json = MenuItemSerializer(menu, many=True).data
        return render(request, self.template_name, {"menu": menu_json}) 

class SingleMenuItem(DetailView):
    model = MenuModel.objects.all()
    template_name = 'menu_item.html'
    
    def get(self, request, id=None):
        try:
            menu_item = MenuModel.objects.get(id=id)    
            menu_item_json = MenuItemSerializer(menu_item).data
        except MenuModel.DoesNotExist:
            raise Http404('Id DOES NOT EXIST')
            
        return render(request, self.template_name, {"menu_item": menu_item_json})
        

restaurant/templates/about.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section>
  <article>
    <h1>About Us</h1>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
        <p>
          Based in Chicago, Illinois, Little Lemon is a family owned
          Mediterranean restaurant, focused on traditional recipes served with a
          modern twist.
        </p>
        <p>
          The chefs draw inspiration from Italian, Greek, and Turkish culture
          and have a menu of 12-15 items that they rotate seasonally.
        </p>

        <p>
          The restaurant has a rustic and relaxed atmosphere with moderate
          prices, making it a popular place for a meal any time of the day.
        </p>

        <p>
          Little Lemon is owned by two Italian brothers, Mario and Adrian, who
          moved to the United States to pursue their shared dream of owning a
          restaurant.
        </p>

        <p>
          To craft the menu, Mario relies on family recipes and his experience
          as a chef in Italy.
        </p>

        <p>
          Adrian does all the marketing for the restaurant and led the effort to
          expand the menu beyond classic Italian to incorporate additional
          cuisines from the mediterranean region.
        </p>
      </div>
      <!--End col-->

      <!--Begin col-->
      <div class="column">
        <figure class="figure">
          <img
            src="{% static 'img/mario-and-adrian.jpg' %}"
            alt="Mario and Adrian"
          />
          <figcaption class="figure-caption">
            Little Lemon owners Mario and Adrian.
          </figcaption>
        </figure>
      </div>
      <!--End col-->
    </div>
    <!--End row-->
  </article>
</section>
{% endblock %}

restaurant/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Little Lemon</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <!--Header content-->
    {% include 'partials/_header.html' %}

    <main>{% block content %} {% endblock %}</main>

    <!--Footer content-->
    {% include 'partials/_footer.html' %} 
    <!-- Replace this comment with your code  -->
  </body>
</html>

restaurant/templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section>
  <article>
    <h1>Make a reservation</h1>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
          <form method="POST" id="form" onsubmit="submitForm(event)">
            {% csrf_token %}
          <p>
              <label for="name">Name:</label>
              <input type="text" placeholder="Your Name" maxlength="200" required id="name">
            </p>
            <p>
              <label for="reservation_date">Reservation date:</label>
              <input id="reservation_date" type="date" required>
            </p>
      
            <p>
              <label for="reservation_slot">Reservation time:</label>
              <select id="reservation_slot" required>
                <option value="0" disabled>Select time</option>
              </select>
            </p>
            <p>
              <label for="no_of_guests">No of Guests:</label>
              <input id="no_of_guests" type="number" required value="1" />
            </p>
            <button type="submit" id="button">Reserve</button>
        </form>
      </div>
      <!--End col-->

      <!--Begin col-->
      <div class="column">
        <h2>Bookings For <span id="today"></span></h2>
        <div id="bookings"></div>
      </div>
      <!--End col-->
    </div>
    <!--End row-->
  </article>
</section>
<script>

  const date = new Date();
  const formattedDate = `${date.getUTCFullYear()}-${(date.getUTCMonth() + 1).toString().padStart(2, "0")}-${date.getUTCDate().toString().padStart(2, "0")}`;
  
  document.getElementById('reservation_date').value = formattedDate;

  getBookings()

  function getBookings() {
    let reserved_slots = []
    const date = document.getElementById('reservation_date').value
    document.getElementById('today').innerHTML = date
    fetch("{% url 'littlelemonAPI:bookings-api' %}" + '?date=' + date)
      .then(r => r.json())
      .then(data => {
        reserved_slots = []
        bookings = ''
        const items = data;   
        
        if (items.length) {
          for (let item of items) {
            reserved_slots.push(item.reservation_slot)
            bookings +=  `<p>${item.name} - ${formatTime(item.reservation_slot)} - Table for ${item.no_of_guests} people</p>`
          }          
        }
      
        let slot_options = '<option value="0" disabled>Select time</option>';

        for (let i = 10; i <= 20; i++) {
          const label = formatTime(i);
          if (reserved_slots.includes(i)) {
            slot_options += `<option value=${i} disabled>${label}</option>`
          } else {
            slot_options += `<option value=${i}>${label}</option>`
          }
        }
        
        document.getElementById('reservation_slot').innerHTML = slot_options
        if (bookings == '') {
          bookings = "<p>No bookings</p>"
        }
        
        document.getElementById('bookings').innerHTML = bookings
      })
  }

  function formatTime(time) {
    const ampm = time < 12 ? 'AM' : 'PM'
    const t = time < 12 ? time : time > 12 ? time - 12 : time
    const label = `${t} ${ampm}`
    return label
  }

  function submitForm(e) {
    e.preventDefault();
    const formData = {
      name: document.getElementById('name').value,
      reservation_date: document.getElementById('reservation_date').value,
      reservation_slot: document.getElementById('reservation_slot').value,
      no_of_guests: document.getElementById('no_of_guests').value
    }

    fetch("{% url 'littlelemonAPI:bookings-api' %}", { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(formData) })
      .then(response => response.text())
      .then(data => {
        getBookings()
      })
  }

  document.getElementById('reservation_date').addEventListener('change', function(e) {
    e.preventDefault();
    getBookings();
  });

</script>
{% endblock %}


restaurant/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section>
    <article id="hero">
      <h1 class="heading_shadow">SPECIAL OFFER</h1>
      <p>
        30% Off This Weekend 
      </p>
      <a href="{% url 'restaurant:book' %}" class="cta"> Book now </a>
    </article>
  </section>
  <section>
    <article>
      <h2>Our New Menu</h2>
      <img src="{% static 'img/Grill.jpg' %}">
      <p>
        Our menu consists of 12-15 seasonal items based on Italian, Greek, and Turkish culture.
      </p>
      <p>
        <a href="{% url 'restaurant:menu' %}">See our new menu</a>
      </p>
    </article>
    <article>
      <h2>Book a table</h2>
      <img src="{% static 'img/salad.jpg' %}">
      <p>
        Reserve your table for an Italian, Greek, and Turkish dining experience.
      </p>
      <p>
        <a href="{% url 'restaurant:book' %}">Book your table now</a>
      </p>
    </article>
    <article>
      <h2>Opening Hours</h2>
      <img src="{% static 'img/head_chef.jpg' %}">
      <p>
        The Little Lemon Restaurant is open 7 days a week, except for public holidays. 
      </p>
      <ul>
        <li>Mon - Fri: 2pm - 10pm</li>
        <li>Sat: 2pm - 11pm</li>
        <li>Sun: 2pm - 9pm</li>
      </ul>
    </article>
  </section>
{% endblock %}

restaurant/templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Menu</h1>
<!--Begin col-->
<div class="column">
    {% for item in menu %}
    <p>
        <a href="{% url 'restaurant:menu-item' id=item.id %}">
            {{ item.title }}
        </a>
        <span class="menu-price">
            ${{ item.price }}.00
        </span>
    </p>
    {% endfor %}
</div>
<!--End col-->
{% endblock %}

restaurant/templates/menu_item.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<section>
   <article>
      <h1>Menu item</h1>
      <span>
         <a href="{% url 'restaurant:home' %}">Home</a> /
         <a href="{% url 'restaurant:menu' %}">Menu</a>/
         {{menu_item.name}}
      </span>
      <!--Begin row-->
      <div class="row">
         <!--Begin col-->
         <div class="column">
            <h2>
                {{ menu_item.title }}
            </h2>
            <p>
                {{ menu_item.menu_item_description }}
            </p>
            <p>
                Price: ${{ menu_item.price }}.00
            </p>
         </div>
         <!--End col-->
         <!--Begin col-->
         <div class="column">
            <img src="{% static 'img/' %}{{menu_item.title}}.jpg" alt="{{ menu_item.title}}" />
        </div>
         <!--End col-->
      </div>
      <!--End row-->
   </article>
</section>
{% endblock %}

restaurant/templates/partials/_footer.html
{% load static %}
<footer>
  <article>
    <img src="{% static 'img/logo_footer.png' %}" />
  </article>
  <article>
    <p>Copyright Little Lemon</p>
  </article>
</footer>

restaurant/templates/partials/_header.html
{% load static %}
<header>
  <img src="{% static 'img/logo.png' %}" />
</header>
<nav>
  <ul>
    <li><a href="{% url 'restaurant:home' %}">Home</a></li>
    <li><a href="{% url 'restaurant:about' %}">About</a></li>
    <li><a href="{% url 'restaurant:menu' %}">Menu</a></li>
    <li><a href="{% url 'restaurant:book' %}">Book</a></li>
    <li><a href="{% url 'restaurant:reservations' %}">Reservations</a></li>
  </ul>
</nav>

restaurant/templates/reservations.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section>
  <article>
    <h1>All Reservations</h1>
    <!--Begin row-->
    <div class="row">
      <!--Begin col-->
      <div class="column">
        <pre id="bookings"></pre>
      </div>
      <!--End col-->

      <!--Begin col-->
      <div class="column">
        <div class="videowrap">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11898.289517452584!2d-87.60853049433447!3d41.79442860243028!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2912ce6f7027%3A0xc0cfb5545d4a37b2!2sHyde%20Park%2C%20Chicago%2C%20IL%2C%20USA!5e0!3m2!1sen!2spt!4v1662384760663!5m2!1sen!2spt"
            width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
      <!--End col-->
    </div>
    <!--End row-->

  </article>
</section>
<script>
  const jsonString = '{{bookings | safe}}';
  const bookings = JSON.parse(jsonString);

  const pretty_json = JSON.stringify(bookings,null,2)
  
  document.getElementById('bookings').innerHTML = pretty_json

</script>
{% endblock %}
